### ISSUE TITLE
你的下载地址在哪儿呢？

### ISSUE THREAD

**Issue by KingDeng** [625781186/gitpyman#1]
本来我想下载下来看看效果呢，可是没有下载地址啊？我又搭建了Python环境，安装源码也不行

**Comment by 625781186** [comment]
> 本来我想下载下来看看效果呢，可是没有下载地址啊？我又搭建了Python环境，安装源码也不行

不好意思 , 暂时没做release . 
还有好多东西要改.
源码安装的报错贴上来我看下 .

-----
发布了0.0.6
可以用命令`pip install gitpyman` 来安装. 
然后在终端运行`gitpyman`.
有报错贴上来我看下.
